version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: "0"
        CACHE_BUST: "${CACHE_BUST:-$(date +%s)}"
      no_cache: true
