name: Docker Image CI/CD for GHCR

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'Dockerfile'
      - 'requirements.txt'
      - '.github/workflows/publish-ghcr.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'Dockerfile'
      - 'requirements.txt'
      - '.github/workflows/publish-ghcr.yml'
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx (for caching)
        uses: docker/setup-buildx-action@v2

      - name: Update version file
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          COMMIT_HASH=${GITHUB_SHA::7}
          echo "${TIMESTAMP}-${COMMIT_HASH}" > version.txt
          echo "Updated version.txt to ${TIMESTAMP}-${COMMIT_HASH}"

      - name: Build and push without caching
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/analyticace/myresumo:latest
          no-cache: true